language: node_js
cache:
  directories:
    - node_modules
node_js:
  - iojs
before_install:
  - npm install -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
